### ISSUE TITLE
【42ページ, 9行目】【質問】 重みの大きさを一定の範囲に収める方法のうち, cの決め方

### ISSUE THREAD

**Issue by haruotsu** [YokoPhys-h/Deep_Learning_Seminar_suzukilab#10]
# 経緯
重みの大きさを一定の範囲に収める方法があるらしいが, そのパラメータ$c$の決め方は適当なのか, なんらかの知見があるのか.

# 内容
$$
\sum w^2_{ji} < c
$$

のパラメータ $c$ の決め方を知りたい.

**Comment by haruotsu** [comment]
大体Try & Errorで決めるらしい.

**Comment by sho7014** [comment]
そんな議論しましたっけ．validationは全部Try & Errorという主張？

**Comment by haruotsu** [comment]
一旦ReOpen

**Comment by haruotsu** [comment]
@sho7014 
めちゃめちゃ急いで雑に書いてました. すみません🙇‍♂️
自分で調整するか, 遺伝アルゴリズムとかハイパーパラメータ探索で決めるという認識で問題ないですかね...

**Comment by sho7014** [comment]
> 遺伝アルゴリズムとかハイパーパラメータ探索

　こういう手法は Try & Error を体系化しただけでは，という信念を持っているのかな，と思いました．

　パラメータの決め方を知りたい，というときは
1. パラメータの良さをどう評価すれば良いのか
2. パラメータの良さを定義した後にどうパラメータを探索すれば良いのか

の２つの問題が現れると思います．  

　これまでの章の内容だと，検証の概念がないのでパラメータ探索の際にパラメータの良さをどう評価すれば良いのか，という話もできないように感じます．テストデータを使って汎化誤差の話をしているので，これを評価指標にしたい気もしますが，テストデータを使ってハイパーパラメータを探索するのはデータリーケージと呼ばれるご法度です．訓練データ，テストデータの他に検証データを用意し，検証データ上での汎化誤差を評価することでハイパーパラメータを良さを評価することになります．この部分（1に対応する部分）は Try & Error というより体系化されています．
　2 の探索について，
> 自分で調整するか, 遺伝アルゴリズムとかハイパーパラメータ探索で決める

これらは全部ハイパーパラメータ探索なので， OR で結ぶ必要はないかと思います．これらを究極的に Try & Error と呼ぶのも否定できないような気はしますが，手動の試行錯誤とベイズ最適化等を一緒くたにしてしまうことになるので，乱暴な感じもしますね．
