### ISSUE TITLE
乱数生成の関数についてのメモ

### ISSUE THREAD

**Issue by Kei-calculation** [YokoPhys-h/Deep_Learning_Seminar_suzukilab#13]
<乱数生成の関数　忘備録>

# 内容
乱数生成の最近の流行りの関数numpy.random.default_rng

numpy.random.default_rngは

default_rngでジェネレータのインスタンスを作る。
インスタンスに対して、確率分布メソッドを呼び出す。

といった工程を踏み、ジェネレータを通して乱数を生成する方がメモリの節約になり、遥かに高速になるため有用。
科学技術計算では大量のデータを扱うため、この利点が嬉しい。
また、生成時のseed値も理解しやすい。

参考サイト
https://www.headboost.jp/numpy-random-default-rng/

**Comment by haruotsu** [comment]
問題あればRe-Openしてください!
