### ISSUE TITLE
【10ページ, 21行目】【質問】 暗黙的にパーセプトロン基準を最適化すればよいことの証明を知りたい

### ISSUE THREAD

**Issue by haruotsu** [YokoPhys-h/Deep_Learning_Seminar_suzukilab#7]
# 経緯

10ページ, 21行目に「パーセプトロンの更新は, 暗黙的にパーセプトロン基準を最適化していることが示されている[41]」とあるが, その証明が見当たらなかった.

# 内容

暗黙的にパーセプトロン基準を最適化すればよいことの証明を知りたい. これは一般に成り立ちますか?

**Comment by sho7014** [comment]
「最適化している（損失関数をパーセプトロン基準としたときの勾配降下法がパーセプトロンの更新と一致する）」と「最適化すればよい（適当なクラスのクラス分類問題についてパーセプトロン基準を利用した勾配降下法が有効に働く）」は異なるので質問の意図がよくわからないです．

前者であれば (1.8) を W について微分すれば良いと思います．定数倍を除いて (1.4) に一致することはすぐわかります．この定数倍の違いは学習率に込めることができます．

後者であれば線形分離可能であればパーセプトロンアルゴリズムは収束することの証明とかでしょうか．これは Duda, Stork & Hart の 定理 5.1 とか読んでください．

**Comment by haruotsu** [comment]
@sho7014 
> 線形分離可能であればパーセプトロンアルゴリズムは収束することの証明

こちらでした. すみません🙇‍♂️
まだ読めてないですが, 多分これだと思うので貼っておきます.
<img width="529" alt="image" src="https://user-images.githubusercontent.com/65439874/200313812-ea99283d-da03-4f7e-99f4-4a9d043edc85.png">
<img width="457" alt="image" src="https://user-images.githubusercontent.com/65439874/200314066-73ce59fd-689a-4e6a-b80d-644874186fb6.png">

**Comment by sho7014** [comment]
テキストの21行目の意図はたぶん後者（パーセプトロンアルゴリズムの収束）を指してるのではなくて前者（パーセプトロン基準の勾配を考えているといいたいだけ）だと思います．
