### ISSUE TITLE
【35ページ，図3.1】【質問】 モメンタムSGDに関する図3.1について理解したい

### ISSUE THREAD

**Issue by kotaro-yoshimura** [YokoPhys-h/Deep_Learning_Seminar_suzukilab#8]
# 経緯

SGDにおいてモメンタムを用いると探索効率が向上する

# 内容

なぜモメンタムによって図3.1のように谷の方向にそって一直線にたどるようになるのか，いまいち理解できていない

**Comment by haruotsu** [comment]
スライドに記載した.
